CLASS LHC_ZR_00_GROCERY_ASHM DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR Grocery_ashm
        RESULT result,
      checkExpirationDte FOR MODIFY
            IMPORTING keys FOR ACTION Grocery_ashm~checkExpirationDte RESULT result.
ENDCLASS.

CLASS LHC_ZR_00_GROCERY_ASHM IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
  METHOD checkExpirationDte.
  ENDMETHOD.

ENDCLASS.
